name: Release Drafter Arangodb
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
#        paths:
#            - 'arangodb/**'
jobs:
    draft_release_arangodb:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-arangodb.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Azureblob
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'azureblob/**'
jobs:
    draft_release_azureblob:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-azureblob.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Badger
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'badger/**'
jobs:
    draft_release_badger:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-badger.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Bbolt
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'bbolt/**'
jobs:
    draft_release_bbolt:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-bbolt.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Dynamodb
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'dynamodb/**'
jobs:
    draft_release_dynamodb:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-dynamodb.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Memcache
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'memcache/**'
jobs:
    draft_release_memcache:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-memcache.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Memory
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'memory/**'
jobs:
    draft_release_memory:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-memory.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Mongodb
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'mongodb/**'
jobs:
    draft_release_mongodb:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-mongodb.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Mssql
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'mssql/**'
jobs:
    draft_release_mssql:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-mssql.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Mysql
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'mysql/**'
jobs:
    draft_release_mysql:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-mysql.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Postgres
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'postgres/**'
jobs:
    draft_release_postgres:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-postgres.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Redis
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'redis/**'
jobs:
    draft_release_redis:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-redis.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Ristretto
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'ristretto/**'
jobs:
    draft_release_ristretto:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-ristretto.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter S3
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 's3/**'
jobs:
    draft_release_s3:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-s3.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Release Drafter Sqlite3
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'sqlite3/**'
jobs:
    draft_release_sqlite3:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-sqlite3.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

