on: [push, pull_request]
name: MongoDB test
jobs:
    mongodb-tests:
        runs-on: ubuntu-latest
        services:
            mongo:
                image: mongo:latest
                ports:
                    - 27017:27017
        strategy:
            matrix:
                go-version: [1.14.x, 1.15.x]
                platform: [ubuntu-latest, windows-latest]
        steps:
            - name: Install Go
              uses: actions/setup-go@v1
              with:
                go-version: ${{ matrix.go-version }}
            - name: Fetch Repository
              uses: actions/checkout@v2
            - name: Run Test
              run: go test ./mongodb -tags=mongodb -v -race
