on: [push, pull_request]
name: MySQL test
jobs:
    mysql-tests:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_DATABASE: fiber
                    MYSQL_USER: username
                    MYSQL_PASSWORD: password
                    MYSQL_ROOT_PASSWORD: password
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd "mysqladmin ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        strategy:
            matrix:
                go-version: [1.14.x, 1.15.x]
        steps:
            - name: Install Go
              uses: actions/setup-go@v1
              with:
                go-version: ${{ matrix.go-version }}
            - name: Fetch Repository
              uses: actions/checkout@v2
            - name: Run Test
              run: go test ./mysql -tags=mysql -v -race
              env:
                MYSQL_USERNAME: username
                MYSQL_PASSWORD: password
                MYSQL_DATABASE: fiber
