on: [push, pull_request]
name: Postgres
jobs:
    Tests:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:latest
                ports:
                    - 5432:5432
                env:
                    POSTGRES_DATABASE: fiber
                    POSTGRES_USER: username
                    POSTGRES_PASSWORD: password
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        strategy:
            matrix:
                go-version: [1.14.x, 1.15.x]
                platform: [ubuntu-latest, windows-latest]
        steps:
            - name: Install Go
              uses: actions/setup-go@v1
              with:
                go-version: ${{ matrix.go-version }}
            - name: Fetch Repository
              uses: actions/checkout@v2
            - name: Run Test
              run: go test ./postgres -tags=postgres -v -race
              env:
                POSTGRES_DATABASE: fiber
                POSTGRES_USER: username
                POSTGRES_PASSWORD: password
